# This workflow will install Python dependencies, 
# lint with a single version of Python, build and run docker.
# In the future it could also test a functionality of the website.

name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build docker
      run: |
        docker build -t deploy-reso .
    - name: Run docker
      run: |
        docker run -d -p 8000:8000 deploy-reso
    - name: Lint with flake8
      run: |
        python -m flake8



